# Generated by Django 3.0.8 on 2020-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_purchasable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
